services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports: 
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.http.routers.${PROJ_NAME:-oldzoomer}.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.${PROJ_NAME:-oldzoomer}.entrypoints=websecure"
      - "traefik.http.routers.${PROJ_NAME:-oldzoomer}.tls.certresolver=myresolver"
      - "traefik.enable=true"
      - "traefik.http.services.${PROJ_NAME:-oldzoomer}.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    external:
      name: traefik
