services:
  nginx:
    image: nginx:stable-alpine
    ports: [80]
    volumes:
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped
    labels:
      - "traefik.http.routers.${PROJ_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJ_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJ_NAME}.tls.certresolver=myresolver"
networks:
  default:
    external:
      name: traefik
