name: Docker Build Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: oldzoomer-react:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
